function [sample_mean sample_cov] = wvfLoadHuman(pupilDiameterMM) %#ok<STOUT>
% Load  mean and covariance of Zernicke coefficients for human data
%
%   [sample_mean sample_cov] = wvfLoadHuman(pupilDiameterMM)
%
% Load statistical summary of the Zernicke polynomial coeffcients measured
% in the human eye.  These come out in OSA order, including the j = 0
% (piston) term.
%
% The data and model are described in 
%   "Retinal Image Quality for Virtual Eyes Generated by a Statistical
%   Model of Ocular Wavefront Aberrations" published in Ophthalmological
%   and Physiological Optics (2009).
%
% Concerning the program, the authors write:
% Permission is granted to use this program for scientific research
% purposes.  Commercial users should contact Indiana University for
% licensing arrangements.
%
% There are no specific comments about the data.
%
% Another relevant paper
%  Autrusseau, Thibos and Shevell (2011)
%   Vision Research
%   Chromatic and wavefront aberrations: L-, M- and S-cone stimulation with
%   typical and extreme retinal image quality
%   http://www.sciencedirect.com/science/article/pii/S0042698911003099
%
% We plan to compare our calculations to the figures in that paper.
%
% Example:
%   pd = 6.0;
%   [sample_mean sample_cov] = vwfLoadHuman(pd);
%
% See Also: s_wvfThibosModel
%
% Copyright Wavefront Toolbox Team, 2012

if ieNotDefined('pupilDiameterMM'), pupilDiameterMM = 6; end

%%
switch pupilDiameterMM
    case 7.5
        load('IASstats75','S','sample_mean');
    case 6.0
        load('IASstats60','S','sample_mean');
    case 4.5
        load('IASstats45','S','sample_mean');
    case 3.0
        load('IASstats30','S','sample_mean');
        
    otherwise
        error('Unknown pupil size')
end

sample_cov = S;

end